# Generated by Django 3.2.9 on 2022-01-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/img/blank_avatar_vuwwgx.png', upload_to='static/img/'),
        ),
    ]
