# Generated by Django 3.2.9 on 2021-12-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_publication_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='user',
            new_name='author',
        ),
    ]
