# Generated by Django 3.2.9 on 2021-12-08 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_as_publication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(related_name='likes_as_publication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
