# Generated by Django 3.2.9 on 2021-12-08 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_auto_20211208_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes_as_publication', to=settings.AUTH_USER_MODEL),
        ),
    ]
