# Generated by Django 3.2.9 on 2021-12-08 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0003_alter_publication_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_as_publication', to=settings.AUTH_USER_MODEL),
        ),
    ]
