# Generated by Django 3.2.9 on 2022-01-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publication_name',
            new_name='name',
        ),
    ]
